#cloud-config

hostname: pi00
manage_etc_hosts: true

users:
  - name: pirate
    primary-group: users
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users,docker,adm,dialout,audio,plugdev,netdev,video
    ssh-import-id: None
    lock_passwd: true
    # set known hosts
    ssh-authorized-keys:
      - ssh-rsa AAAA...NNNN

# define ssh key for master node
ssh_keys:
  rsa_private: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ...
    -----END OPENSSH PRIVATE KEY-----

  rsa_public: ssh-rsa AAAA...NNNN

resize_rootfs: true
growpart:
    mode: auto
    devices: ["/"]
    ignore_growroot_disabled: false

package_update: true
package_upgrade: true
package_reboot_if_required: true

locale: "de_DE.UTF-8"
timezone: "Europe/Berlin"

# Static IP address
write_files:
  - content: |
      persistent
      # Generate Stable Private IPv6 Addresses instead of hardware based ones
      slaac private
      # static IP configuration:
      interface eth0
      static ip_address=10.0.0.145/23
      static routers=194.94.192.35
      static domain_name_servers=194.94.192.35 8.8.8.8
    path: /etc/dhcpcd.conf
# These commands will be ran once on first boot only
runcmd:
  # Pickup the hostname changes
  - 'systemctl restart avahi-daemon'